// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using login_api_iw_js.Data;

#nullable disable

namespace login_api_iw_js.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ObjetivoTema", b =>
                {
                    b.Property<int>("ObjetivosId")
                        .HasColumnType("int");

                    b.Property<int>("TemasId")
                        .HasColumnType("int");

                    b.HasKey("ObjetivosId", "TemasId");

                    b.HasIndex("TemasId");

                    b.ToTable("TemaObjetivo", (string)null);
                });

            modelBuilder.Entity("Progreso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Escala")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("HitoId")
                        .HasColumnType("int");

                    b.Property<int>("ObjetivoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("ValorObtenido")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HitoId");

                    b.HasIndex("UsuarioId", "ObjetivoId");

                    b.ToTable("Progreso");
                });

            modelBuilder.Entity("Tema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Tema");
                });

            modelBuilder.Entity("UsuarioObjetivo", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("ObjetivoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("datetime2");

                    b.HasKey("UsuarioId", "ObjetivoId");

                    b.HasIndex("ObjetivoId");

                    b.ToTable("UsuarioObjetivo");
                });

            modelBuilder.Entity("login_api_iw_js.LoginApi_Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("login_api_iw_js.Models.Hito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Calificacion")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ObjetivoId")
                        .HasColumnType("int");

                    b.Property<int>("TemaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ObjetivoId");

                    b.HasIndex("TemaId");

                    b.ToTable("Hito");
                });

            modelBuilder.Entity("login_api_iw_js.Models.Objetivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Objetivo");
                });

            modelBuilder.Entity("login_api_iw_js.Models.Subtema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HitoId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("RecursoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HitoId");

                    b.ToTable("Subtema");
                });

            modelBuilder.Entity("ObjetivoTema", b =>
                {
                    b.HasOne("login_api_iw_js.Models.Objetivo", null)
                        .WithMany()
                        .HasForeignKey("ObjetivosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tema", null)
                        .WithMany()
                        .HasForeignKey("TemasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Progreso", b =>
                {
                    b.HasOne("login_api_iw_js.Models.Hito", "Hito")
                        .WithMany("Progresos")
                        .HasForeignKey("HitoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UsuarioObjetivo", "UsuarioObjetivo")
                        .WithMany("Progresos")
                        .HasForeignKey("UsuarioId", "ObjetivoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hito");

                    b.Navigation("UsuarioObjetivo");
                });

            modelBuilder.Entity("UsuarioObjetivo", b =>
                {
                    b.HasOne("login_api_iw_js.Models.Objetivo", "Objetivo")
                        .WithMany("UsuarioObjetivos")
                        .HasForeignKey("ObjetivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("login_api_iw_js.LoginApi_Models.Usuario", "Usuario")
                        .WithMany("UsuarioObjetivos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Objetivo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("login_api_iw_js.Models.Hito", b =>
                {
                    b.HasOne("login_api_iw_js.Models.Objetivo", "Objetivo")
                        .WithMany("Hitos")
                        .HasForeignKey("ObjetivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tema", "Tema")
                        .WithMany("Hitos")
                        .HasForeignKey("TemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Objetivo");

                    b.Navigation("Tema");
                });

            modelBuilder.Entity("login_api_iw_js.Models.Subtema", b =>
                {
                    b.HasOne("login_api_iw_js.Models.Hito", "Hito")
                        .WithMany("Subtemas")
                        .HasForeignKey("HitoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hito");
                });

            modelBuilder.Entity("Tema", b =>
                {
                    b.Navigation("Hitos");
                });

            modelBuilder.Entity("UsuarioObjetivo", b =>
                {
                    b.Navigation("Progresos");
                });

            modelBuilder.Entity("login_api_iw_js.LoginApi_Models.Usuario", b =>
                {
                    b.Navigation("UsuarioObjetivos");
                });

            modelBuilder.Entity("login_api_iw_js.Models.Hito", b =>
                {
                    b.Navigation("Progresos");

                    b.Navigation("Subtemas");
                });

            modelBuilder.Entity("login_api_iw_js.Models.Objetivo", b =>
                {
                    b.Navigation("Hitos");

                    b.Navigation("UsuarioObjetivos");
                });
#pragma warning restore 612, 618
        }
    }
}
